[package]
name = "komf-notifications"
version = "0.1.0"
edition = "2021"

[dependencies]
komf-core = { path = "../komf-core" }
reqwest = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
mime_guess = { workspace = true }
